name: MATLAB on self-hosted runner

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run_matlab:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v4

      - name: Run main (print MATLAB error)
        shell: powershell
        run: |
          chcp 65001
          matlab -batch "try; cd(getenv('GITHUB_WORKSPACE')); addpath(genpath(pwd)); main_learning_rmpc; catch e; disp(getReport(e,'extended','hyperlinks','off')); exit(1); end; exit(0);"
