name: MATLAB on self-hosted runner

on:
  workflow_dispatch:
  push:

jobs:
  run_matlab:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v4

      - name: Run main script
        shell: powershell
        run: |
          matlab -batch "main_learning_rmpc"
